import * as THREE from "https://cdn.jsdelivr.net/npm/three@0.180.0/build/three.module.js";

export function createArchitectScene(host){
const clamp=(v,a=0,b=1)=>Math.max(a,Math.min(b,v));
const smoothstep=t=>{t=clamp(t);return t*t*(3-2*t)};
const lerp=(a,b,t)=>a+(b-a)*t;
const progressBetween=(t,a,b)=>clamp((t-a)/(b-a));
function easeInOutCubic(t){t=clamp(t);return t<.5?4*t*t*t:1-Math.pow(-2*t+2,3)/2}
function easeOutCubic(t){return 1-Math.pow(1-clamp(t),3)}
function easeOutQuart(t){return 1-Math.pow(1-clamp(t),4)}
function easeOutBack(t){t=clamp(t);const c1=1.70158,c3=c1+1;return 1+c3*Math.pow(t-1,3)+c1*Math.pow(t-1,2)}

const renderer=new THREE.WebGLRenderer({antialias:true,alpha:true,powerPreference:"high-performance"});renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setClearColor(0xffffff,0);renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;host.appendChild(renderer.domElement);const scene=new THREE.Scene();scene.background=null;scene.fog=new THREE.Fog(0xffffff,20,33);const camera=new THREE.PerspectiveCamera(48,1,.1,100),CAMERA_TARGET=new THREE.Vector3(0,2.25,0),START_CAMERA_ANGLE=.79,CAMERA_RADIUS=15.8;function setCamera(angle,height=7.3){camera.position.set(Math.cos(angle)*CAMERA_RADIUS,height,Math.sin(angle)*CAMERA_RADIUS);camera.lookAt(CAMERA_TARGET)}setCamera(START_CAMERA_ANGLE);scene.add(new THREE.HemisphereLight(0xffffff,0xeeeeee,2.8));const sun=new THREE.DirectionalLight(0xffffff,3.2);sun.position.set(6,12,8);sun.castShadow=true;sun.shadow.mapSize.set(1024,1024);sun.shadow.camera.left=-12;sun.shadow.camera.right=12;sun.shadow.camera.top=12;sun.shadow.camera.bottom=-12;scene.add(sun);
const GROUND_SLAB_H=.24,GROUND_SLAB_TOP=.24,GROUND_WALL_H=2.62,UPPER_SLAB_H=.24,UPPER_SLAB_Y=GROUND_SLAB_TOP+GROUND_WALL_H,UPPER_SLAB_TOP=UPPER_SLAB_Y+UPPER_SLAB_H,UPPER_FLOOR_H=2.25,ROOF_H=.17,BUILDING_W=5.75,BUILDING_D=4.60;
function createBoxGroup(w,h,d,o={}){const g=new THREE.Group(),geo=new THREE.BoxGeometry(w,h,d),mat=new THREE.MeshStandardMaterial({color:o.color??0xf8f8f8,roughness:.95,metalness:0,transparent:true,opacity:o.opacity??.92}),m=new THREE.Mesh(geo,mat);m.castShadow=true;m.receiveShadow=true;g.add(m);const e=new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:o.edgeColor??0x252525,transparent:true,opacity:o.edgeOpacity??.62}));g.add(e);return g}function createVerticalBox(w,h,d,o={}){const g=new THREE.Group(),geo=new THREE.BoxGeometry(w,h,d);geo.translate(0,h/2,0);const mat=new THREE.MeshStandardMaterial({color:o.color??0xf8f8f8,roughness:.96,metalness:0,transparent:true,opacity:o.opacity??.9}),m=new THREE.Mesh(geo,mat);m.castShadow=true;m.receiveShadow=true;g.add(m);g.add(new THREE.LineSegments(new THREE.EdgesGeometry(geo),new THREE.LineBasicMaterial({color:o.edgeColor??0x222222,transparent:true,opacity:o.edgeOpacity??.68})));return g}function setObjectOpacity(o,s,l=s){o.traverse(c=>{if(!c.material)return;c.material.transparent=true;c.material.opacity=(c.isLine||c.isLineSegments)?l:s})}
const TERRAIN_SIZE=13.8,TERRAIN_DIVISIONS=16,terrainOriginal=[],vertexPositions=[],gridCount=TERRAIN_DIVISIONS+1;function terrainHeight(x,z){return Math.sin(x*.72)*.28+Math.cos(z*.61)*.22+Math.sin((x+z)*.39)*.16+Math.cos((x-z)*.51)*.11}for(let zi=0;zi<=TERRAIN_DIVISIONS;zi++)for(let xi=0;xi<=TERRAIN_DIVISIONS;xi++){const x=-TERRAIN_SIZE/2+xi/TERRAIN_DIVISIONS*TERRAIN_SIZE,z=-TERRAIN_SIZE/2+zi/TERRAIN_DIVISIONS*TERRAIN_SIZE,h=terrainHeight(x,z);vertexPositions.push(x,0,z);terrainOriginal.push({x,z,h})}const terrainIndices=[];for(let z=0;z<TERRAIN_DIVISIONS;z++)for(let x=0;x<TERRAIN_DIVISIONS;x++){const a=z*gridCount+x,b=a+1,c=(z+1)*gridCount+x,d=c+1;(x+z)%2===0?terrainIndices.push(a,c,b,b,c,d):terrainIndices.push(a,c,d,a,d,b)}const terrainGeometry=new THREE.BufferGeometry();terrainGeometry.setAttribute("position",new THREE.Float32BufferAttribute(vertexPositions,3));terrainGeometry.setIndex(terrainIndices);terrainGeometry.computeVertexNormals();const terrainMaterial=new THREE.MeshStandardMaterial({color:0xf6f6f6,roughness:1,metalness:0,side:THREE.DoubleSide,flatShading:true,transparent:true,opacity:0}),terrainMesh=new THREE.Mesh(terrainGeometry,terrainMaterial);terrainMesh.receiveShadow=true;scene.add(terrainMesh);const terrainWireMaterial=new THREE.MeshBasicMaterial({color:0x797979,wireframe:true,transparent:true,opacity:0}),terrainWire=new THREE.Mesh(terrainGeometry,terrainWireMaterial);terrainWire.position.y=.006;scene.add(terrainWire);
const groundSlab=createBoxGroup(BUILDING_W,GROUND_SLAB_H,BUILDING_D,{color:0xf7f7f7,opacity:.95,edgeOpacity:.75});groundSlab.position.y=GROUND_SLAB_H/2;scene.add(groundSlab);const rearWallWidth=BUILDING_W/2-.05,rearWallDepth=.18,leftRearWall=createBoxGroup(rearWallWidth,GROUND_WALL_H,rearWallDepth,{color:0xf8f8f8,opacity:.93,edgeOpacity:.72});leftRearWall.position.set(-BUILDING_W/4,GROUND_SLAB_TOP+GROUND_WALL_H/2,-BUILDING_D/2+.18);scene.add(leftRearWall);const rightRearWall=createBoxGroup(rearWallWidth,GROUND_WALL_H,rearWallDepth,{color:0xf8f8f8,opacity:.93,edgeOpacity:.72});rightRearWall.position.set(BUILDING_W/4,GROUND_SLAB_TOP+GROUND_WALL_H/2,-BUILDING_D/2+.18);rightRearWall.rotation.y=Math.PI;scene.add(rightRearWall);const column=createVerticalBox(.30,GROUND_WALL_H,.30,{color:0xf5f5f5,opacity:.96,edgeOpacity:.82});column.position.set(-1.72,GROUND_SLAB_TOP,1.74);column.scale.y=0;scene.add(column);const columnRight=createVerticalBox(.30,GROUND_WALL_H,.30,{color:0xf5f5f5,opacity:.96,edgeOpacity:.82});columnRight.position.set(1.72,GROUND_SLAB_TOP,1.74);columnRight.scale.y=0;scene.add(columnRight);const upperSlab=createBoxGroup(6.15,UPPER_SLAB_H,5,{color:0xf6f6f6,opacity:.95,edgeOpacity:.76});upperSlab.position.y=UPPER_SLAB_Y+UPPER_SLAB_H/2;scene.add(upperSlab);
const marginGroup=new THREE.Group();scene.add(marginGroup);const marginY=UPPER_SLAB_TOP+.016,marginW=5.42,marginD=4.28;function makeDynamicLine(a,b){const pos=new Float32Array(6),geo=new THREE.BufferGeometry();geo.setAttribute("position",new THREE.BufferAttribute(pos,3));const line=new THREE.Line(geo,new THREE.LineBasicMaterial({color:0x242424,transparent:true,opacity:0}));line.userData.start=a.clone();line.userData.end=b.clone();return line}const marginLines=[makeDynamicLine(new THREE.Vector3(-marginW/2,marginY,-marginD/2),new THREE.Vector3(marginW/2,marginY,-marginD/2)),makeDynamicLine(new THREE.Vector3(marginW/2,marginY,-marginD/2),new THREE.Vector3(marginW/2,marginY,marginD/2)),makeDynamicLine(new THREE.Vector3(marginW/2,marginY,marginD/2),new THREE.Vector3(-marginW/2,marginY,marginD/2)),makeDynamicLine(new THREE.Vector3(-marginW/2,marginY,marginD/2),new THREE.Vector3(-marginW/2,marginY,-marginD/2))];marginLines.forEach(l=>marginGroup.add(l));function animateDynamicLine(line,t){t=easeInOutCubic(t);const a=line.userData.start,b=line.userData.end,c=new THREE.Vector3().lerpVectors(a,b,t),p=line.geometry.attributes.position.array;p[0]=a.x;p[1]=a.y;p[2]=a.z;p[3]=c.x;p[4]=c.y;p[5]=c.z;line.geometry.attributes.position.needsUpdate=true;line.material.opacity=.78*clamp(t*2)}
const upperFloor=new THREE.Group();upperFloor.position.y=UPPER_SLAB_TOP;scene.add(upperFloor);function addUpperWall(w,d,x,z){const wall=createVerticalBox(w,UPPER_FLOOR_H,d,{color:0xf9f9f9,opacity:.82,edgeOpacity:.65});wall.position.set(x,0,z);upperFloor.add(wall);return wall}const upperWalls=[addUpperWall(.16,marginD,-marginW/2,0),addUpperWall(.16,marginD,marginW/2,0),addUpperWall(marginW,.16,0,-marginD/2),addUpperWall(2.35,.16,-1.50,marginD/2),addUpperWall(.18,.16,2.50,marginD/2)];upperWalls.forEach(w=>w.scale.y=0);
const windowGroup=new THREE.Group(),windowWidth=2.42,windowHeight=1.68,windowGeometry=new THREE.PlaneGeometry(windowWidth,windowHeight),windowMaterial=new THREE.MeshPhysicalMaterial({color:0xdceef7,transparent:true,opacity:.52,roughness:.12,transmission:.13,side:THREE.DoubleSide}),windowPane=new THREE.Mesh(windowGeometry,windowMaterial);windowGroup.add(windowPane);const windowFrame=new THREE.LineSegments(new THREE.EdgesGeometry(windowGeometry),new THREE.LineBasicMaterial({color:0x39434a,transparent:true,opacity:.58}));windowGroup.add(windowFrame);const mullion=new THREE.Line(new THREE.BufferGeometry().setFromPoints([new THREE.Vector3(0,-windowHeight/2,.005),new THREE.Vector3(0,windowHeight/2,.005)]),new THREE.LineBasicMaterial({color:0x5c6870,transparent:true,opacity:.32}));windowGroup.add(mullion);const WINDOW_TARGET_X=1.2;windowGroup.position.set(WINDOW_TARGET_X,UPPER_SLAB_TOP+1.13,marginD/2+.092);scene.add(windowGroup);windowGroup.visible=false;const roof=createBoxGroup(6.48,ROOF_H,5.28,{color:0xf7f7f7,opacity:.94,edgeOpacity:.76}),ROOF_TARGET_Y=UPPER_SLAB_TOP+UPPER_FLOOR_H+.12;roof.position.y=ROOF_TARGET_Y;roof.rotation.x=-.055;scene.add(roof);
const trees=[],treeLocations=[{x:-4.15,z:-2.35,h:1.38,r:.45},{x:3.95,z:-2.65,h:1.52,r:.49},{x:-3.55,z:3.35,h:1.22,r:.40},{x:3.75,z:3.05,h:1.44,r:.46},{x:.15,z:-4.05,h:1.24,r:.39}];function createTree(d){const g=new THREE.Group(),stemGeo=new THREE.BufferGeometry();stemGeo.setAttribute("position",new THREE.BufferAttribute(new Float32Array([0,0,0,0,0,0]),3));const stem=new THREE.Line(stemGeo,new THREE.LineBasicMaterial({color:0x4c4c4c,transparent:true,opacity:0}));g.add(stem);const crown=new THREE.Mesh(new THREE.SphereGeometry(d.r,16,12),new THREE.MeshStandardMaterial({color:0x743d3d,roughness:.9,transparent:true,opacity:.86}));crown.position.y=d.h;crown.scale.setScalar(0);crown.castShadow=true;g.add(crown);g.position.set(d.x,terrainHeight(d.x,d.z),d.z);g.userData={height:d.h,stem,crown};scene.add(g);trees.push(g)}treeLocations.forEach(createTree);
function createTextSprite(text){const c=document.createElement("canvas");c.width=512;c.height=128;const x=c.getContext("2d");x.font="600 42px Helvetica Neue, Arial";x.fillStyle="rgba(20,20,20,.98)";x.textAlign="center";x.textBaseline="middle";x.fillText(text,256,64);const tex=new THREE.CanvasTexture(c);tex.colorSpace=THREE.SRGBColorSpace;const s=new THREE.Sprite(new THREE.SpriteMaterial({map:tex,transparent:true,opacity:0,depthTest:false,depthWrite:false}));s.scale.set(1.58,.395,1);s.renderOrder=12;return s}const dimensions=new THREE.Group();dimensions.renderOrder=10;scene.add(dimensions);function makeDimension(start,end,label,pos){const geo=new THREE.BufferGeometry().setFromPoints([start,start.clone()]),line=new THREE.Line(geo,new THREE.LineDashedMaterial({color:0x292929,transparent:true,opacity:0,dashSize:.18,gapSize:.12,depthTest:false,depthWrite:false}));line.renderOrder=11;line.computeLineDistances();dimensions.add(line);const text=createTextSprite(label);text.position.copy(pos);dimensions.add(text);return{line,text,start,end}}const dimensionObjects=[makeDimension(new THREE.Vector3(-BUILDING_W/2,.18,2.66),new THREE.Vector3(BUILDING_W/2,.18,2.66),"5.75 m",new THREE.Vector3(0,.54,2.70)),makeDimension(new THREE.Vector3(3.08,.18,-BUILDING_D/2),new THREE.Vector3(3.08,.18,BUILDING_D/2),"4.60 m",new THREE.Vector3(3.08,.54,0)),makeDimension(new THREE.Vector3(-3.05,.16,2.08),new THREE.Vector3(-3.05,ROOF_TARGET_Y+.18,2.08),"5.52 m",new THREE.Vector3(-3.05,3.02,2.08))];function animateDimension(d,t){t=easeInOutCubic(t);const cur=new THREE.Vector3().lerpVectors(d.start,d.end,t),a=d.line.geometry.attributes.position.array;a[0]=d.start.x;a[1]=d.start.y;a[2]=d.start.z;a[3]=cur.x;a[4]=cur.y;a[5]=cur.z;d.line.geometry.attributes.position.needsUpdate=true;d.line.computeLineDistances();d.line.material.opacity=.82*t;d.text.material.opacity=clamp((t-.58)/.42)*.98}
const greenStart=new THREE.Color(0xf6f6f6),greenEnd=new THREE.Color(0xdce5da);function updateTerrain(time){const fade=smoothstep(progressBetween(time,.25,1.75));terrainMaterial.opacity=fade*.92;terrainWireMaterial.opacity=fade*.52;const rise=easeInOutCubic(progressBetween(time,1.75,4.65)),flat=easeInOutCubic(progressBetween(time,4.65,6.45)),pos=terrainGeometry.attributes.position.array;for(let i=0;i<terrainOriginal.length;i++){const pt=terrainOriginal[i],rd=Math.max(Math.abs(pt.x)/3.55,Math.abs(pt.z)/2.95);let w=0;if(rd<=.84)w=1;else if(rd<1.10)w=1-smoothstep((rd-.84)/.26);pos[i*3+1]=pt.h*rise*(1-flat*w)}terrainGeometry.attributes.position.needsUpdate=true;terrainGeometry.computeVertexNormals();terrainMaterial.color.copy(greenStart).lerp(greenEnd,easeInOutCubic(progressBetween(time,20.8,23.4)))}
function updateBuilding(time){let t=easeOutCubic(progressBetween(time,6.25,8.15));groundSlab.position.y=lerp(GROUND_SLAB_H/2+7,GROUND_SLAB_H/2,t);setObjectOpacity(groundSlab,.95*t,.76*t);t=easeOutQuart(progressBetween(time,8.05,9.95));leftRearWall.position.x=lerp(-BUILDING_W/4-5.6,-BUILDING_W/4,t);setObjectOpacity(leftRearWall,.93*t,.72*t);let raw=progressBetween(time,9.40,11.35);t=easeOutQuart(raw);rightRearWall.position.x=lerp(BUILDING_W/4+5.7,BUILDING_W/4,t);rightRearWall.rotation.y=lerp(Math.PI*1.55,Math.PI,t);setObjectOpacity(rightRearWall,.93*t,.72*t);t=easeInOutCubic(progressBetween(time,10.75,12.50));column.scale.y=t;setObjectOpacity(column,.96*t,.82*t);const columnRightT=easeInOutCubic(progressBetween(time,10.95,12.70));columnRight.scale.y=columnRightT;setObjectOpacity(columnRight,.96*columnRightT,.82*columnRightT);t=easeOutCubic(progressBetween(time,12.15,14.05));upperSlab.position.y=lerp(UPPER_SLAB_Y+UPPER_SLAB_H/2+7.3,UPPER_SLAB_Y+UPPER_SLAB_H/2,t);setObjectOpacity(upperSlab,.95*t,.76*t);for(let i=0;i<marginLines.length;i++){const s=13.85+i*.32;animateDynamicLine(marginLines[i],progressBetween(time,s,s+.75))}t=easeInOutCubic(progressBetween(time,15.15,17.95));upperWalls.forEach(w=>{w.scale.y=t;setObjectOpacity(w,.86*t,.66*t)});raw=progressBetween(time,17.65,19.80);t=easeOutCubic(raw);windowGroup.visible=raw>0;if(raw>0){windowGroup.position.x=lerp(WINDOW_TARGET_X+4.8,WINDOW_TARGET_X,t);windowMaterial.opacity=.52*t;windowFrame.material.opacity=.58*t;mullion.material.opacity=.32*t}t=easeOutCubic(progressBetween(time,19.35,21.45));roof.position.y=lerp(ROOF_TARGET_Y+6.8,ROOF_TARGET_Y,t);roof.rotation.x=lerp(.01,-.055,t);setObjectOpacity(roof,.94*t,.76*t)}
function updateTrees(time){trees.forEach((tree,i)=>{const s=23.10+i*.30,stemT=easeOutCubic(progressBetween(time,s,s+.90)),a=tree.userData.stem.geometry.attributes.position.array;a[0]=0;a[1]=0;a[2]=0;a[3]=0;a[4]=tree.userData.height*stemT;a[5]=0;tree.userData.stem.geometry.attributes.position.needsUpdate=true;tree.userData.stem.material.opacity=.60*stemT;tree.userData.crown.scale.setScalar(easeOutBack(progressBetween(time,s+.55,s+1.42)))})}function updateDimensions(time){dimensionObjects.forEach((d,i)=>{const s=25.35+i*.52;animateDimension(d,progressBetween(time,s,s+1.50))})}function updateCamera(time){const orbit=easeInOutCubic(progressBetween(time,27.75,36.5));setCamera(START_CAMERA_ANGLE+orbit*1.36,lerp(7.3,3.8,orbit))}

function resize(){const r=host.getBoundingClientRect(),w=Math.max(1,r.width),h=Math.max(1,r.height);renderer.setPixelRatio(Math.min(devicePixelRatio||1,2));renderer.setSize(w,h,false);camera.aspect=w/h;camera.updateProjectionMatrix()}
function renderAt(time){updateTerrain(time);updateBuilding(time);updateTrees(time);updateDimensions(time);updateCamera(time);renderer.render(scene,camera)}
return {resize,renderAt};
}
